---
- name: creating team user 
  become: true
  hosts: all
  tasks: 
    - name: Creating user
      user: name=Abdul password=password
    - name: Creating user
      user: name=Zafar password=password
    - name: Creating user
      user: name=Vlad password=password
    - name: Creating user
      user: name=Hugo password=password
    - name: Creating user
      user: name=Miki password=password
    - name: Creating user
      user: name=Arif password=password   


