---
#
# Playbook to install nagios server, clients and
# generate service checks based on Ansible inventory
#

# we need to collect facts from all hosts we reference
# https://github.com/ansible/ansible/issues/9260
# we skip switches/oobservers because they normally don't
# have python installed.

- hosts: all:!switches:!oobservers:!idrac:!supermicro_6048r:!supermicro_6018r:!supermicro_1028r:!devices
  remote_user:  ansible
  become: true
  tasks: []

# role for nagios clients via NRPE
- hosts: all:!switches:!oobservers:!nagios:!idrac:!supermicro_6048r:!supermicro_6018r:!supermicro_1028r:!freenas:!devices
  remote_user: ansible
  become: true
  roles:
    - { role: nagios_client }
    - { role: firewall_client, when: manage_firewall_client|bool }

# role for nagios server
- hosts: nagios
  remote_user:  ansible 
  become: true
  roles:
    - { role: nagios }
    - { role: firewall, when: manage_firewall|bool }
    - { role: instructions }
