# roles/mailserver/defaults/main.yml
---
postfix_myhostname: 'prdx-mail11.ziyotek1.local'

postfix_mydomain: 'ziyotek1.local'

postfix_home_mailbox: 'mail/'

spamassassin_packages:
  - spamassassin

clamav_packages:
  - clamav-server
  - clamav-data
  - clamav-update
  - clamav-filesystem
  - clamav
  - clamav-scanner-systemd
  - clamav-devel
  - clamav-lib
  - clamav-server-systemd
postfix_mynetwork:
  - 0.0.0.0/0
postfix_ldap: true 

ldap_fqdn1: prdx-ldap11.ziyotek1.local

ldap_ou: users

ldap_dcname: prdx-ldap11

ldap_domainname: ziyotek1

ldap_root_domain: local
