---
- name: Install mysql and Php
  hosts: db
  become: true
  roles:
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.mysql
    - geerlingguy.phpmyadmin
  tasks:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted  
